export const ROUTES = {
  HOME: "/",
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  RESET_PASSWORD: "/auth/reset-password",
  COMICS: "/comics",
  SEARCH: "/search",
  COMIC_DETAIL: (id: string) => `/comics/${id}`,
  CHAPTER_READER: (comicId: string, chapterId: string) =>
    `/comics/${comicId}/chapter/${chapterId}`,
  PLACEHOLDER_COVER: "/placeholder-cover.jpg",
  USER: {
    ROOT: "/user",
    PROFILE: "/user/profile",
    DASHBOARD: "/user/dashboard",
    FAVORITES: "/user/bookmarks",
    HISTORY: "/user/history",
  },
  ADMIN: {
    ROOT: "/admin",
    DASHBOARD: "/admin/dashboard",
    COMICS: "/admin/comics",
    CHAPTERS: "/admin/chapters",
    USERS: "/admin/users",
    CATEGORIES: "/admin/categories",
    AUTHORS: "/admin/authors",
    SETTINGS: "/admin/settings",
    ADS: "/admin/ads",
    AUDIT: "/admin/audit",
    OPERATIONS: "/admin/operations",
    ANALYTICS: "/admin/analytics",
    PROFILE: "/admin/profile",
  },
  ERROR: {
    UNAUTHORIZED: "/handle-exception/401",
    FORBIDDEN: "/handle-exception/403",
  },
  API: {
    HEALTH: "/api/health",
    ANALYTICS: "/api/analytics",
    AVATAR: "/api/avatar",
    CATEGORIES: "/api/categories",
    R2_PROXY: "/api/r2/proxy",
    R2_UPLOAD: "/api/r2/upload",
    WEBHOOKS_SUPABASE: "/api/webhooks/supabase",
  },
} as const;
