// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/auth/reset-password" | "/forbidden" | "/handle-exception/400" | "/handle-exception/401" | "/handle-exception/403" | "/handle-exception/404" | "/handle-exception/503" | "/story/[storyId]/chapter/[chapterId]" | "/unauthorized"
type AppRouteHandlerRoutes = "/api/auth/verify-recovery" | "/api/chapters" | "/api/internal/admin/audit" | "/api/internal/admin/manage-chapter" | "/api/internal/admin/manage-story" | "/api/internal/admin/profiles" | "/api/internal/admin/taxonomy" | "/api/role-distribution" | "/api/rpc/increment-story-views" | "/api/rpc/like-story" | "/api/rpc/unlike-story" | "/api/site-metrics" | "/api/site-settings" | "/api/stories" | "/api/system-settings" | "/api/taxonomy/categories"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/auth/verify-recovery": {}
  "/api/chapters": {}
  "/api/internal/admin/audit": {}
  "/api/internal/admin/manage-chapter": {}
  "/api/internal/admin/manage-story": {}
  "/api/internal/admin/profiles": {}
  "/api/internal/admin/taxonomy": {}
  "/api/role-distribution": {}
  "/api/rpc/increment-story-views": {}
  "/api/rpc/like-story": {}
  "/api/rpc/unlike-story": {}
  "/api/site-metrics": {}
  "/api/site-settings": {}
  "/api/stories": {}
  "/api/system-settings": {}
  "/api/taxonomy/categories": {}
  "/auth/reset-password": {}
  "/forbidden": {}
  "/handle-exception/400": {}
  "/handle-exception/401": {}
  "/handle-exception/403": {}
  "/handle-exception/404": {}
  "/handle-exception/503": {}
  "/story/[storyId]/chapter/[chapterId]": { "storyId": string; "chapterId": string; }
  "/unauthorized": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
