// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forbidden/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forbidden">> = Specific
  const handler = {} as typeof import("../../src/app/forbidden/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/handle-exception/400/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/handle-exception/400">> = Specific
  const handler = {} as typeof import("../../src/app/handle-exception/400/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/handle-exception/401/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/handle-exception/401">> = Specific
  const handler = {} as typeof import("../../src/app/handle-exception/401/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/handle-exception/403/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/handle-exception/403">> = Specific
  const handler = {} as typeof import("../../src/app/handle-exception/403/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/handle-exception/404/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/handle-exception/404">> = Specific
  const handler = {} as typeof import("../../src/app/handle-exception/404/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/handle-exception/503/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/handle-exception/503">> = Specific
  const handler = {} as typeof import("../../src/app/handle-exception/503/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/story/[storyId]/chapter/[chapterId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/story/[storyId]/chapter/[chapterId]">> = Specific
  const handler = {} as typeof import("../../src/app/story/[storyId]/chapter/[chapterId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/unauthorized/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unauthorized">> = Specific
  const handler = {} as typeof import("../../src/app/unauthorized/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/verify-recovery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-recovery">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/verify-recovery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chapters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chapters">> = Specific
  const handler = {} as typeof import("../../src/app/api/chapters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/internal/admin/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/admin/audit">> = Specific
  const handler = {} as typeof import("../../src/app/api/internal/admin/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/internal/admin/manage-chapter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/admin/manage-chapter">> = Specific
  const handler = {} as typeof import("../../src/app/api/internal/admin/manage-chapter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/internal/admin/manage-story/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/admin/manage-story">> = Specific
  const handler = {} as typeof import("../../src/app/api/internal/admin/manage-story/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/internal/admin/profiles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/admin/profiles">> = Specific
  const handler = {} as typeof import("../../src/app/api/internal/admin/profiles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/internal/admin/taxonomy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/admin/taxonomy">> = Specific
  const handler = {} as typeof import("../../src/app/api/internal/admin/taxonomy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/role-distribution/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/role-distribution">> = Specific
  const handler = {} as typeof import("../../src/app/api/role-distribution/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rpc/increment-story-views/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rpc/increment-story-views">> = Specific
  const handler = {} as typeof import("../../src/app/api/rpc/increment-story-views/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rpc/like-story/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rpc/like-story">> = Specific
  const handler = {} as typeof import("../../src/app/api/rpc/like-story/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rpc/unlike-story/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rpc/unlike-story">> = Specific
  const handler = {} as typeof import("../../src/app/api/rpc/unlike-story/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/site-metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site-metrics">> = Specific
  const handler = {} as typeof import("../../src/app/api/site-metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/site-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site-settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/site-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stories">> = Specific
  const handler = {} as typeof import("../../src/app/api/stories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/system-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system-settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/system-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/taxonomy/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/taxonomy/categories">> = Specific
  const handler = {} as typeof import("../../src/app/api/taxonomy/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
