// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forbidden/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forbidden">> = Specific
  const handler = {} as typeof import("../../src/app/forbidden/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/handle-exception/400/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/handle-exception/400">> = Specific
  const handler = {} as typeof import("../../src/app/handle-exception/400/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/handle-exception/401/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/handle-exception/401">> = Specific
  const handler = {} as typeof import("../../src/app/handle-exception/401/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/handle-exception/403/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/handle-exception/403">> = Specific
  const handler = {} as typeof import("../../src/app/handle-exception/403/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/handle-exception/404/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/handle-exception/404">> = Specific
  const handler = {} as typeof import("../../src/app/handle-exception/404/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/handle-exception/503/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/handle-exception/503">> = Specific
  const handler = {} as typeof import("../../src/app/handle-exception/503/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/story/[storyId]/chapter/[chapterId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/story/[storyId]/chapter/[chapterId]">> = Specific
  const handler = {} as typeof import("../../src/app/story/[storyId]/chapter/[chapterId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/unauthorized/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unauthorized">> = Specific
  const handler = {} as typeof import("../../src/app/unauthorized/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
